# Functions to retrieve the features of an input article

In [39]:
import pandas as pd
import matplotlib.pyplot as plt
from textblob import TextBlob
import nltk
import numpy as np
import scipy
import sklearn

## Get the article text

In [40]:
from goose3 import Goose

In [41]:
def get_text(url):
    g = Goose()
    article = g.extract(url=url)
    return article.cleaned_text

### Testing

In [42]:
test_article = get_text("https://abcnews.go.com/Technology/wireStory/finding-health-advice-social-media-easier-knowing-claims-120054862")
print(test_article)

In the corners of social media dominated by wellness content, influencers recommend an assortment of treatments and products to support weight loss, fight exhaustion or promote other desired health outcomes

In the corners of social media dominated by wellness content, influencers recommend an assortment of treatments and products to support weight loss, fight exhaustion or promote other desired health outcomes.

Some of the endorsed approaches may be helpful. Many play into fads with scant evidence to back up enthusiasts' claims, medical experts say.

Some influencers encourage their followers to avoid specific food items, such as seed oils, while others advocate going all in on certain foods, such as the meat-heavy carnivore diet. There are video pitches for berberine, a chemical compound that’s been touted online as “nature’s Ozempic,” and for non-medical IV vitamin therapy, which businesses popularly known as drip bars market as cures for hangovers or fatigue.

To be sure, alternative health practices and cures that lacked the medical establishment's backing were a part of popular culture long before the internet age. But the plethora of advice shared online has both prompted calls for safeguards and found a measure of mainstream acceptance.

The new U.S. health secretary, Robert F. Kennedy Jr., had his Instagram account suspended in 2021 for posting misinformation about vaccine safety and COVID-19, but many of the ideas he champions have a widespread following. Critics of Dr. Mehmet Oz accused him of sometimes making misleading assertions on the talk show he used to host; Oz now is President Donald Trump's nominee to lead the Centers for Medicaid and Medicare Services.

A Netflix series released last month explored the story of Belle Gibson, a popular Australian wellness influencer who amassed a following talking about curing her terminal brain cancer with a healthy lifestyle and alternative medicine. In 2015, Gibson admitted to lying about having a cancer diagnosis. Australia’s federal court later fined her for failing to donate money she said would go to charity through sales of her cookbook and app.

With personal wellness remaining a hot topic, here are some tips health experts have for evaluating the material you see online:

Most influencers have or want business relationships with companies that allow them to earn income by promoting products. The arrangements don't necessarily mean content creators don’t believe in what they’re marketing, but they do have a vested interest in publicizing products that may or may not work.

Creators can get paid for pictures or videos that hype up a product and also earn commissions on sales through features such as affiliate links. Experts note it's therefore better to proceed with caution when someone inspires you to hit the “buy” button, whether it's for natural supplements, teas with purported weight loss benefits or any other wellness products that show up in your social media feed.

Research published last month in the Journal of the American Medical Association showed a sizable amount of Instagram and TikTok posts that discussed five popular medical tests mostly came from account holders with “some form of financial interest” in promoting the screenings.

After analyzing roughly 980 posts on the two platforms, researchers said most of the posts they found were misleading and failed to “mention important harms, including overdiagnosis” resulting from health people having full-body MRIs or tests to detect early signs of cancer, evaluate microorganisms in the gut or measure hormone levels.

Promoting dietary supplements has been a particularly lucrative exercise for many influencers, said Timothy Caulfield, a health policy and law professor at the University of Alberta. He views the supplements industry as “the backbone” of health misinformation aimed at consumers and designed to fuel billions of dollars in revenue.

“It’s gotten to the point where if someone is selling a supplement, it’s a red flag,” he said. "I don’t think it was always like that, but it certainly is now.”

In general, consumers should take all bold claims with a degree of skepticism, said Cedric Bryant, chief executive officer at the nonprofit American Council on Exercise. The goal of creators is to increase engagement with their content, and some influencers may be tempted to make unproven assertions to draw in more viewers.

“If it’s too good to be true, it probably is,” Bryant said.

Some health and wellness influencers have medical training, but many do not. Before taking health tips from someone on social media, it’s a good idea to make sure they have the proper expertise or at least able to share the data that led them to recommend certain products or lifestyle choices.

In the fitness area, Bryant recommends checking to see if a creator holds certification from an accreditation organization and then confirming the information through the U.S. Registry of Exercise Professionals database.

The American Medical Association and The American Board of Medical Specialties maintain searchable databases for medical doctors, which may help verify the qualifications of creators who share their legal names and general locations. States also operate databases that allow users to check if someone is licensed to practice medicine or has been disciplined for misconduct.

If an influencer holding the appropriate credentials pushes certain products, consumers still may want to consider if a brand partnership or other factors are shaping their recommendations.

Federal Trade Commission guidelines that reflected the agency's interpretation of federal law directed influencers featuring specific products or services to prominently disclose any endorsements. Yet sponsorships and potential conflicts of interest are not always revealed.

In 2023, the year the guidelines were issued, the FTC issued warnings to a dozen online influencers for failing to adequately disclose paid social media posts that promoted “sugar-containing products” and aspartame, a sweetener found in diet soda, ice cream and other foods. Some of the influencers were registered dieticians.

If a creator cites studies to support health and diet claims, it’s best to check and see if what they’re saying aligns with the latest evidence-based medical consensus.

“Just because somebody has an ‘M.D.’ after their name doesn’t make them entirely trustworthy,” said Elias Aboujaoude, a psychiatrist and Stanford University professor who studies the intersection of psychology and technology.

Aboujaoude suggests double-checking health claims with traditionally reputable sources, such as major academic institutions or government health agencies. He also advised looking at studies cited by creators and assessing whether they’ve been published in reputable journals and subjected to peer review.

In some cases, it might be too soon to know if promising results should be trusted or not, said Katherine Zeratsky, a registered dietitian with the Mayo Clinic in Minnesota. For example, a study might show the benefits of a specific type of herb. But that doesn’t necessarily mean the findings have been replicated in other research, a requirement for treatment methods to be considered proven effective, she said.

## Getting rid of any smart quotes

In [43]:
# removing strange characters
def clean_encoding(text):
    text = text = text.replace('â€˜', "'").replace('â€™', "'").replace('â€œ', '"').replace('â€', '"')
    text = text.replace('â€“', '–').replace('â€”', '—').replace('â€', '')
    text = text.replace("“", '"').replace("”", '"').replace("’", "'").replace("‘", "'")
    return text

### Testing

In [44]:
test_article = clean_encoding(test_article)
print(test_article)

In the corners of social media dominated by wellness content, influencers recommend an assortment of treatments and products to support weight loss, fight exhaustion or promote other desired health outcomes

In the corners of social media dominated by wellness content, influencers recommend an assortment of treatments and products to support weight loss, fight exhaustion or promote other desired health outcomes.

Some of the endorsed approaches may be helpful. Many play into fads with scant evidence to back up enthusiasts' claims, medical experts say.

Some influencers encourage their followers to avoid specific food items, such as seed oils, while others advocate going all in on certain foods, such as the meat-heavy carnivore diet. There are video pitches for berberine, a chemical compound that's been touted online as "nature's Ozempic," and for non-medical IV vitamin therapy, which businesses popularly known as drip bars market as cures for hangovers or fatigue.

To be sure, alternative health practices and cures that lacked the medical establishment's backing were a part of popular culture long before the internet age. But the plethora of advice shared online has both prompted calls for safeguards and found a measure of mainstream acceptance.

The new U.S. health secretary, Robert F. Kennedy Jr., had his Instagram account suspended in 2021 for posting misinformation about vaccine safety and COVID-19, but many of the ideas he champions have a widespread following. Critics of Dr. Mehmet Oz accused him of sometimes making misleading assertions on the talk show he used to host; Oz now is President Donald Trump's nominee to lead the Centers for Medicaid and Medicare Services.

A Netflix series released last month explored the story of Belle Gibson, a popular Australian wellness influencer who amassed a following talking about curing her terminal brain cancer with a healthy lifestyle and alternative medicine. In 2015, Gibson admitted to lying about having a cancer diagnosis. Australia's federal court later fined her for failing to donate money she said would go to charity through sales of her cookbook and app.

With personal wellness remaining a hot topic, here are some tips health experts have for evaluating the material you see online:

Most influencers have or want business relationships with companies that allow them to earn income by promoting products. The arrangements don't necessarily mean content creators don't believe in what they're marketing, but they do have a vested interest in publicizing products that may or may not work.

Creators can get paid for pictures or videos that hype up a product and also earn commissions on sales through features such as affiliate links. Experts note it's therefore better to proceed with caution when someone inspires you to hit the "buy" button, whether it's for natural supplements, teas with purported weight loss benefits or any other wellness products that show up in your social media feed.

Research published last month in the Journal of the American Medical Association showed a sizable amount of Instagram and TikTok posts that discussed five popular medical tests mostly came from account holders with "some form of financial interest" in promoting the screenings.

After analyzing roughly 980 posts on the two platforms, researchers said most of the posts they found were misleading and failed to "mention important harms, including overdiagnosis" resulting from health people having full-body MRIs or tests to detect early signs of cancer, evaluate microorganisms in the gut or measure hormone levels.

Promoting dietary supplements has been a particularly lucrative exercise for many influencers, said Timothy Caulfield, a health policy and law professor at the University of Alberta. He views the supplements industry as "the backbone" of health misinformation aimed at consumers and designed to fuel billions of dollars in revenue.

"It's gotten to the point where if someone is selling a supplement, it's a red flag," he said. "I don't think it was always like that, but it certainly is now."

In general, consumers should take all bold claims with a degree of skepticism, said Cedric Bryant, chief executive officer at the nonprofit American Council on Exercise. The goal of creators is to increase engagement with their content, and some influencers may be tempted to make unproven assertions to draw in more viewers.

"If it's too good to be true, it probably is," Bryant said.

Some health and wellness influencers have medical training, but many do not. Before taking health tips from someone on social media, it's a good idea to make sure they have the proper expertise or at least able to share the data that led them to recommend certain products or lifestyle choices.

In the fitness area, Bryant recommends checking to see if a creator holds certification from an accreditation organization and then confirming the information through the U.S. Registry of Exercise Professionals database.

The American Medical Association and The American Board of Medical Specialties maintain searchable databases for medical doctors, which may help verify the qualifications of creators who share their legal names and general locations. States also operate databases that allow users to check if someone is licensed to practice medicine or has been disciplined for misconduct.

If an influencer holding the appropriate credentials pushes certain products, consumers still may want to consider if a brand partnership or other factors are shaping their recommendations.

Federal Trade Commission guidelines that reflected the agency's interpretation of federal law directed influencers featuring specific products or services to prominently disclose any endorsements. Yet sponsorships and potential conflicts of interest are not always revealed.

In 2023, the year the guidelines were issued, the FTC issued warnings to a dozen online influencers for failing to adequately disclose paid social media posts that promoted "sugar-containing products" and aspartame, a sweetener found in diet soda, ice cream and other foods. Some of the influencers were registered dieticians.

If a creator cites studies to support health and diet claims, it's best to check and see if what they're saying aligns with the latest evidence-based medical consensus.

"Just because somebody has an 'M.D.' after their name doesn't make them entirely trustworthy," said Elias Aboujaoude, a psychiatrist and Stanford University professor who studies the intersection of psychology and technology.

Aboujaoude suggests double-checking health claims with traditionally reputable sources, such as major academic institutions or government health agencies. He also advised looking at studies cited by creators and assessing whether they've been published in reputable journals and subjected to peer review.

In some cases, it might be too soon to know if promising results should be trusted or not, said Katherine Zeratsky, a registered dietitian with the Mayo Clinic in Minnesota. For example, a study might show the benefits of a specific type of herb. But that doesn't necessarily mean the findings have been replicated in other research, a requirement for treatment methods to be considered proven effective, she said.

## Get Word Count

In [45]:
def get_article_word_count(article):
    return len(article.split())

## Getting Overall Polarity and Subjectivity

In [46]:

def find_polarity(article):
    news = TextBlob(article)
    return news.sentiment.polarity

def find_subjectivity(article):
    news = TextBlob(article)
    return news.sentiment.subjectivity

## Getting Average Polarity and Subjectivity by Sentence

In [47]:
def find_avg_polarity_sentences(article):
    news = TextBlob(article)
    polarity = []
    for sentence in news.sentences:
        polarity.append(sentence.sentiment.polarity)
    return sum(polarity) / len(polarity)

def find_avg_subjectivity_sentences(article):
    news = TextBlob(article)
    subjectivity = []
    for sentence in news.sentences:
        subjectivity.append(sentence.sentiment.subjectivity)
    return sum(subjectivity) / len(subjectivity)

## Getting Approximate Speech Attributes

##### (number of times "said", or "say" appears in the article)

In [55]:
# testing shows that "say" includes "saying", so no need to count over again.

def get_num_quotes(text):
    text = text.lower()
    return text.count("said") + text.count("say") + text.count("told") + text.count("tell")

In [49]:
def create_article_info(article):
    article_info = {}
    article_info['word_count'] = get_article_word_count(article)
    article_info['polarity'] = find_polarity(article)
    article_info['subjectivity'] = find_subjectivity(article)
    article_info['avg_polarity'] = find_avg_polarity_sentences(article)
    article_info['avg_subjectivity'] = find_avg_subjectivity_sentences(article)
    article_info['num_quotes'] = get_num_quotes(article)
    article_info = pd.DataFrame(article_info, index=[0])
    return article_info

In [50]:
def get_article_info(url):
    article = get_text(url)
    article = clean_encoding(article)
    article_info = create_article_info(article)
    return article_info

### Testing

In [51]:
get_article_info("https://abcnews.go.com/Technology/wireStory/finding-health-advice-social-media-easier-knowing-claims-120054862")

,word_count,polarity,subjectivity,avg_polarity,avg_subjectivity,num_quotes
0,1124,0.166642,0.389137,0.134409,0.33742,11

In [ ]:
# add error message for when the article is not found

In [52]:
url = "https://www.reddit.com/r/NoContract/comments/1ern5h9/cheapest_burner_phone_all_i_need_it_for_is_texting/?rdt=48123"

In [53]:
get_article_info(url)

,word_count,polarity,subjectivity,avg_polarity,avg_subjectivity,num_quotes
0,30,0.487778,0.716667,0.162593,0.238889,2

In [54]:
get_text(url)

"TItle says it all. It would be great if I can order it directly from somewhere as I can't get around very easily. it can be the dumbest phone around"